### ISSUE TITLE
issue with cruft

### ISSUE THREAD

**Issue by dornech** [callowayproject/generate-changelog#40]
I have an issue when trying to cruft my package.
https://github.com/cruft/cruft/issues/319

It seems to me that this is caused by the yml-internal variable mechanism in .changelog-config.yml. If not used so often, replacing the variable by it's value is OK but not really in line with the documentation. I guess with being able to reference pyproject.toml in the yml-file, this would overcome the issue with cruft.

**Comment by coordt** [comment]
I think you can fix your issue by escaping this in your template: https://jinja.palletsprojects.com/en/stable/templates/#escaping

Instead of:

```yaml
starting_tag_pipeline:
  - action: ReadFile
    kwargs:
      filename: "{{ changelog_filename }}"
```

Use:

```yaml
starting_tag_pipeline:
  - action: ReadFile
    kwargs:
      filename: "{% raw %}{{ changelog_filename }}{% endraw %}"
```
